#    ░░░░░██╗██╗░░░██╗██╗██╗░░░░░███████╗░█████╗░██████╗░██████╗░░█████╗░███╗░░██╗░██████╗
#    ░░░░░██║██║░░░██║██║██║░░░░░██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗████╗░██║██╔════╝
#    ░░░░░██║██║░░░██║██║██║░░░░░█████╗░░███████║██║░░██║██║░░██║██║░░██║██╔██╗██║╚█████╗░
#    ██╗░░██║██║░░░██║██║██║░░░░░██╔══╝░░██╔══██║██║░░██║██║░░██║██║░░██║██║╚████║░╚═══██╗
#    ╚█████╔╝╚██████╔╝██║███████╗███████╗██║░░██║██████╔╝██████╔╝╚█████╔╝██║░╚███║██████╔╝
#    ░╚════╝░░╚═════╝░╚═╝╚══════╝╚══════╝╚═╝░░╚═╝╚═════╝░╚═════╝░░╚════╝░╚═╝░░╚══╝╚═════╝░
# Deverloper by JuileStudio, JuileCraft, XXXpaziXXX
# Support vk - @xzyoname


#  ░██████╗██████╗░███████╗██╗░░██╗
#  ██╔════╝██╔══██╗██╔════╝██║░██╔╝
#  ╚█████╗░██████╔╝█████╗░░█████═╝░
#  ░╚═══██╗██╔═══╝░██╔══╝░░██╔═██╗░
#  ██████╔╝██║░░░░░███████╗██║░╚██╗
#  ╚═════╝░╚═╝░░░░░╚══════╝╚═╝░░╚═╝

messages:
  noPermission: 'Нету прав:D'
  usage: 'Использование- /jc check|uncheck|reload'
  reload.yes: 'Конфиг перезагружен'
  checknoprm: 'Вы не можете это использывать сейчас!'
  checkyes: 'Вы пошли на проверку'
  unchecknoprm: 'Вы не можете это использывать сейчас!'
  uncheckyes: 'Вы успешно вышли с проверки'
  noplayercheck: 'Игрока нету на сервере'
  reset: 'Игроку %toplayer%'
  nocmd: 'Команды нет, иди нафиг'

# ████████╗██╗███╗░░░███╗███████╗░█████╗░██╗░░██╗░█████╗░████████╗
# ╚══██╔══╝██║████╗░████║██╔════╝██╔══██╗██║░░██║██╔══██╗╚══██╔══╝
# ░░░██║░░░██║██╔████╔██║█████╗░░██║░░╚═╝███████║███████║░░░██║░░░
# ░░░██║░░░██║██║╚██╔╝██║██╔══╝░░██║░░██╗██╔══██║██╔══██║░░░██║░░░
# ░░░██║░░░██║██║░╚═╝░██║███████╗╚█████╔╝██║░░██║██║░░██║░░░██║░░░
# ░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚══════╝░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░

sec-need-time: 900 # какое время должен провести игрок на сервере, что бы смог писать в чат
time-actions:
  - '[MESSAGE] &cОШИБКА: &7Вы не отыграли на сервере &c15 минут!'
  - '[TITLE] &cОШИБКА:%nl&fВы должны поиграть &c15 минут!'
  - '[SOUND] ENTITY_VILLAGER_NO;6;1'

#  ██████╗░░█████╗░████████╗██╗░█████╗░███╗░░██╗████████╗██╗███╗░░░███╗███████╗
#  ██╔══██╗██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║╚══██╔══╝██║████╗░████║██╔════╝
#  ██████╔╝██║░░██║░░░██║░░░██║██║░░██║██╔██╗██║░░░██║░░░██║██╔████╔██║█████╗░░
#  ██╔═══╝░██║░░██║░░░██║░░░██║██║░░██║██║╚████║░░░██║░░░██║██║╚██╔╝██║██╔══╝░░
#  ██║░░░░░╚█████╔╝░░░██║░░░██║╚█████╔╝██║░╚███║░░░██║░░░██║██║░╚═╝░██║███████╗
#  ╚═╝░░░░░░╚════╝░░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚══════╝

Settings:
  item:
    name: '&e&lОТЗЫВАНИЕ'
    lore:
      - ''
      - '&fЗапоминает ваши координаты'
      - '&fи через &e1 минуту &fтелепортирует'
      - '&fВас обратно на них'
  #Время в секундах
  time: 60
  #Боссбар
  bossbar: '&fВремя до телепортации: &e#time#'
